from __future__ import annotations

from enum import Enum


class ReportPeriod(str, Enum):
    D7 = "7d"
    D30 = "30d"
    D90 = "90d"
    ALL = "all"
    CUSTOM = "custom"


class EventType(str, Enum):
    BUY = "buy"
    SELL = "sell"
    TRANSFER_IN = "transferIn"
    TRANSFER_OUT = "transferOut"
    ADD = "add"
    REMOVE = "remove"
    UNKNOWN = "unknown"


class AcquisitionType(str, Enum):
    BUY = "BUY"
    TRANSFER_IN = "TRANSFER_IN"
    BRIDGE = "BRIDGE"
    WRAPPED = "WRAPPED"
    AIRDROP = "AIRDROP"
    MINT = "MINT"
    UNKNOWN = "UNKNOWN"


class AcquisitionStatus(str, Enum):
    VERIFIED = "VERIFIED"
    INFERRED = "INFERRED"
    NO_BUY_HISTORY = "NO_BUY_HISTORY"
    API_UNAVAILABLE = "API_UNAVAILABLE"


class FieldStatus(str, Enum):
    KNOWN = "KNOWN"
    VERIFIED = "VERIFIED"
    CONSENSUS = "CONSENSUS"
    DIRECT = "DIRECT"
    DERIVED = "DERIVED"
    NOT_APPLICABLE = "NOT_APPLICABLE"
    UNKNOWN = "UNKNOWN"
    ESTIMATED = "ESTIMATED"
    API_MISSING = "API_MISSING"
    UNRESOLVED = "UNRESOLVED"
    CONFLICT = "CONFLICT"
    ERROR = "ERROR"


class DataSource(str, Enum):
    SOLANA_RPC = "SOLANA_RPC"
    MORALIS = "MORALIS"
    HELIUS = "HELIUS"
    DEXSCREENER = "DEXSCREENER"
    JUPITER = "JUPITER"
    GECKOTERMINAL = "GECKOTERMINAL"
    PUMPFUN = "PUMPFUN"
    DEFILLAMA = "DEFILLAMA"
    RAYDIUM = "RAYDIUM"
    GMGN = "GMGN"
    LOCAL_CALCULATION = "LOCAL_CALCULATION"
    SPECIAL_ASSET_REGISTRY = "SPECIAL_ASSET_REGISTRY"


class ResolutionStatus(str, Enum):
    VERIFIED = "VERIFIED"
    CONSENSUS = "CONSENSUS"
    DIRECT = "DIRECT"
    DERIVED = "DERIVED"
    ESTIMATED = "ESTIMATED"
    NOT_APPLICABLE = "NOT_APPLICABLE"
    UNRESOLVED = "UNRESOLVED"
    CONFLICT = "CONFLICT"


class ProviderHealth(str, Enum):
    HEALTHY = "HEALTHY"
    DEGRADED = "DEGRADED"
    RATE_LIMITED = "RATE_LIMITED"
    UNAVAILABLE = "UNAVAILABLE"
    AUTH_FAILED = "AUTH_FAILED"
    PLAN_UNAVAILABLE = "PLAN_UNAVAILABLE"
    CIRCUIT_OPEN = "CIRCUIT_OPEN"
    OPTIONAL = "OPTIONAL"
    NOT_CONFIGURED = "NOT_CONFIGURED"
    DISABLED = "DISABLED"
    THROTTLED = "THROTTLED"
    COOLDOWN = "COOLDOWN"


class HeliusCapStatus(str, Enum):
    AVAILABLE = "AVAILABLE"
    PLAN_UNAVAILABLE = "PLAN_UNAVAILABLE"
    AUTH_FAILED = "AUTH_FAILED"
    NOT_FOUND = "NOT_FOUND"
    UNKNOWN = "UNKNOWN"
    TEMPORARY_ERROR = "TEMPORARY_ERROR"
    NOT_CONFIGURED = "NOT_CONFIGURED"


class ProviderCapability(str, Enum):
    WALLET_SWAPS = "WALLET_SWAPS"
    WALLET_HISTORY = "WALLET_HISTORY"
    WALLET_TRANSFERS = "WALLET_TRANSFERS"
    WALLET_BALANCES = "WALLET_BALANCES"
    TOKEN_METADATA = "TOKEN_METADATA"
    TOKEN_MARKET = "TOKEN_MARKET"
    TOKEN_POOLS = "TOKEN_POOLS"
    TRANSACTION_DETAIL = "TRANSACTION_DETAIL"
    TOKEN_CREATION = "TOKEN_CREATION"
    HISTORICAL_PRICE = "HISTORICAL_PRICE"
    PNL = "PNL"
    LAUNCHPAD = "LAUNCHPAD"


class CircuitState(str, Enum):
    CLOSED = "CLOSED"
    OPEN = "OPEN"
    HALF_OPEN = "HALF_OPEN"


class VerificationMode(str, Enum):
    FAST = "FAST"
    BALANCED = "BALANCED"
    STRICT = "STRICT"


class TaskStatus(str, Enum):
    WAITING = "WAITING"
    WAITING_API = "WAITING_API"
    RETRYING = "RETRYING"
    RUNNING = "RUNNING"
    SUCCESS = "SUCCESS"
    PARTIAL = "PARTIAL"
    WARNING = "WARNING"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class ApiHealth(str, Enum):
    OK = "API 正常"
    WAITING = "等待限频"
    COOLDOWN = "429 冷却"


class TokenPositionStatus(str, Enum):
    OPEN = "仍持仓"
    CLOSED = "已清仓"
    UNKNOWN = "持仓未知"
